# Generated by Django 6.0 on 2025-12-20 09:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('region', models.CharField(choices=[('URR', 'URR'), ('LRR', 'LRR'), ('CRR', 'CRR'), ('NBR1', 'NBR1'), ('NBR2', 'NBR2'), ('BANJUL_KOMBO', 'BANJUL KOMBO'), ('WEST_COAST', 'WEST COAST')], max_length=20)),
                ('majilis', models.CharField(choices=[('ATAFL', 'ATAFL'), ('Khuddam', 'Khuddam'), ('ANSAR', 'ANSAR'), ('GUEST', 'GUEST')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='tagnid.registration')),
            ],
            options={
                'verbose_name': 'Vitals',
                'verbose_name_plural': 'Vitals',
                'ordering': ['-created_at'],
            },
        ),
    ]
