# Generated by Django 6.0 on 2025-12-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagnid', '0003_add_unique_code_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='auxiliary_body',
            field=models.CharField(choices=[('Atfal', 'Atfal'), ('Khuddam', 'Khuddam'), ('Ansar', 'Ansar'), ('Guest', 'Guest')], max_length=20, verbose_name='Auxiliary Body'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='region',
            field=models.CharField(choices=[('URR', 'URR'), ('LRR', 'LRR'), ('CRR', 'CRR'), ('NBR1', 'NBR1'), ('NBR2', 'NBR2'), ('BANJUL_KOMBO', 'BANJUL KOMBO'), ('FONI', 'FONI')], max_length=20),
        ),
    ]
