# Generated by Django 6.0 on 2026-04-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagnid', '0004_alter_registration_auxiliary_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='auxiliary_body',
            field=models.CharField(choices=[('Atfal', 'Atfal'), ('Khuddam', 'Khuddam'), ('Ansar', 'Ansar'), ('Guest', 'Guest'), ('Lajina', 'Lajina'), ('Nasrat', 'Nasrat')], max_length=20, verbose_name='Auxiliary Body'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('year', models.PositiveIntegerField()),
                ('database_key', models.CharField(help_text='Database alias/key to route this program data (e.g. default, railway_2026).', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'year'), name='unique_program_name_year')],
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='tagnid.program'),
        ),
    ]
