# Generated by Django 6.0 on 2026-04-09 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagnid', '0005_registration_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='database_key',
        ),
        migrations.AlterField(
            model_name='registration',
            name='auxiliary_body',
            field=models.CharField(choices=[('Atfal', 'Atfal'), ('Khuddam', 'Khuddam'), ('Ansar', 'Ansar'), ('Guest', 'Guest'), ('Lajina', 'Lajina'), ('Nasirat', 'Nasirat')], max_length=20, verbose_name='Auxiliary Body'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('program_manager', 'Program Manager'), ('male_data_entry', 'Male Data Entry'), ('female_data_entry', 'Female Data Entry'), ('viewer', 'Viewer')], default='male_data_entry', max_length=30)),
                ('default_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='tagnid.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
