# Generated by Django 6.0 on 2026-04-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagnid', '0006_remove_program_database_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived programs are hidden from users but data is preserved.'),
        ),
    ]
