# Generated by Django 6.0 on 2026-04-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagnid', '0007_program_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='unique_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Unique Registration Code'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('program', 'unique_code'), name='unique_code_per_program'),
        ),
    ]
