# Generated by Django 6.0 on 2026-04-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagnid', '0008_alter_registration_unique_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='auxiliary_body',
            field=models.CharField(choices=[('Atfal', 'Atfal'), ('Khuddam', 'Khuddam'), ('Ansar', 'Ansar'), ('Guest', 'Guest'), ('Foreign_Delegate', 'Foreign Delegate'), ('Lajina', 'Lajina'), ('Nasirat', 'Nasirat')], max_length=20, verbose_name='Auxiliary Body'),
        ),
    ]
